# Generated by Django 3.2.2 on 2021-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interno',
            name='profecion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interno',
            name='sexo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
